# API Documentation for Authentication and User Management

### Auth - Signup
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "username": "user",
  "email": "user@gmail.com",
  "password": "User@123"
}

###

### Auth - SignIn
POST http://localhost:8080/api/auth/signIn
Content-Type: application/json

{
  "username": "admin",
  "password": "Admin@123"
}

###

### Users - Create User
POST http://localhost:8080/api/users
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "username": "belay",
  "email": "belay@gmail.com",
  "password": "Belay@123",
  "role": "USER"
}

###

### Users - Find All Users
GET http://localhost:8080/api/users
Authorization: Bearer {{authToken}}

###

### Users - Find User by ID
GET http://localhost:8080/api/users/{{userId}}
Authorization: Bearer {{authToken}}

###

### Users - Update User by ID
PUT http://localhost:8080/api/users/{{userId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "username": "belay",
  "email": "belay@gmail.com",
  "password": "Belay@123",
  "role": "USER"
}

###

### Users - Delete User by ID
DELETE http://localhost:8080/api/users/{{userId}}
Authorization: Bearer {{authToken}}

